#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 10, 2018 03:36:11 PM +07  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

from . import blend_support


def vp_start_gui():
    """Starting point when module is the main routine."""
    global val, w, root
    root = Tk()
    top = Blender(root)
    blend_support.init(root, top)
    root.mainloop()


def vp_init_gui():
    """Starting point when module is the main routine."""
    global val, w, root
    root = Tk()
    root.resizable(False, False)
    top = Blender(root)
    blend_support.init(root, top)
    return root, top


w = None


def create_Blender(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel(root)
    top = Blender(w)
    blend_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Blender():
    global w
    w.destroy()
    w = None


class Blender:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#d9d9d9'  # X11 color: 'gray85'

        top.geometry("1120x670")
        top.title("Blender")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.616, rely=0.0, relheight=0.493
                               , relwidth=0.375)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Result''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=420)

        self.can_main = Canvas(self.Labelframe1)
        self.can_main.place(relx=0.024, rely=0.061, height=300
                            , width=400, bordermode='ignore')
        self.can_main.configure(background="#d9d9d9")
        self.can_main.configure(highlightbackground="#d9d9d9")
        self.can_main.configure(highlightcolor="black")
        self.can_main.configure(insertbackground="black")
        self.can_main.configure(relief=RIDGE)
        self.can_main.configure(selectbackground="#c4c4c4")
        self.can_main.configure(selectforeground="black")

        self.menubar = Menu(top, font="TkMenuFont", bg=_bgcolor, fg=_fgcolor)
        top.configure(menu=self.menubar)

        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.009, rely=0.0, relheight=0.493
                               , relwidth=0.375)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Image 1''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=420)

        self.can_im1 = Canvas(self.Labelframe2)
        self.can_im1.place(relx=0.024, rely=0.061, height=300
                           , width=400, bordermode='ignore')
        self.can_im1.configure(background="#d9d9d9")
        self.can_im1.configure(cursor="crosshair")
        self.can_im1.configure(highlightbackground="#d9d9d9")
        self.can_im1.configure(highlightcolor="black")
        self.can_im1.configure(insertbackground="black")
        self.can_im1.configure(selectbackground="#c4c4c4")
        self.can_im1.configure(selectforeground="black")
        # self.can_im1.configure(width=202)

        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.009, rely=0.493, relheight=0.493
                               , relwidth=0.375)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Image 2''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=420)

        self.can_im2 = Canvas(self.Labelframe3)
        self.can_im2.place(relx=0.024, rely=0.061, height=300
                           , width=400, bordermode='ignore')
        self.can_im2.configure(background="#d9d9d9")
        self.can_im2.configure(cursor="crosshair")
        self.can_im2.configure(highlightbackground="#d9d9d9")
        self.can_im2.configure(highlightcolor="black")
        self.can_im2.configure(insertbackground="black")
        self.can_im2.configure(relief=RIDGE)
        self.can_im2.configure(selectbackground="#c4c4c4")
        self.can_im2.configure(selectforeground="black")

        self.btn_blend = Button(top)
        self.btn_blend.place(relx=0.866, rely=0.925, height=33, width=137)
        self.btn_blend.configure(activebackground="#d9d9d9")
        self.btn_blend.configure(activeforeground="#000000")
        self.btn_blend.configure(background="#d9d9d9")
        self.btn_blend.configure(disabledforeground="#a3a3a3")
        self.btn_blend.configure(foreground="#000000")
        self.btn_blend.configure(foreground="#000000")
        self.btn_blend.configure(highlightbackground="#d9d9d9")
        self.btn_blend.configure(highlightcolor="black")
        self.btn_blend.configure(pady="0")
        self.btn_blend.configure(text='''Blend it!!!''')
        self.btn_blend.configure(width=137)

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.384, rely=0.0, relheight=0.493
                               , relwidth=0.223)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Coors 1''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(width=250)

        self.Frame1 = Frame(self.Labelframe4)
        self.Frame1.place(relx=0.04, rely=0.091, relheight=0.136, relwidth=0.94
                          , bordermode='ignore')
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief=GROOVE)
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=235)

        self.Label1 = Label(self.Frame1)
        self.Label1.place(relx=0.043, rely=0.222, height=26, width=31)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''NW''')

        self.entry_nw1x = Entry(self.Frame1)
        self.entry_nw1x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_nw1x.configure(background="white")
        self.entry_nw1x.configure(disabledforeground="#a3a3a3")
        self.entry_nw1x.configure(font="TkFixedFont")
        self.entry_nw1x.configure(foreground="#000000")
        self.entry_nw1x.configure(insertbackground="black")
        self.entry_nw1x.configure(width=84)

        self.entry_nw1y = Entry(self.Frame1)
        self.entry_nw1y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_nw1y.configure(background="white")
        self.entry_nw1y.configure(disabledforeground="#a3a3a3")
        self.entry_nw1y.configure(font="TkFixedFont")
        self.entry_nw1y.configure(foreground="#000000")
        self.entry_nw1y.configure(insertbackground="black")
        self.entry_nw1y.configure(width=84)

        self.Frame1_1 = Frame(self.Labelframe4)
        self.Frame1_1.place(relx=0.04, rely=0.242, relheight=0.136, relwidth=0.94
                            , bordermode='ignore')
        self.Frame1_1.configure(relief=GROOVE)
        self.Frame1_1.configure(borderwidth="2")
        self.Frame1_1.configure(relief=GROOVE)
        self.Frame1_1.configure(background="#d9d9d9")
        self.Frame1_1.configure(highlightbackground="#d9d9d9")
        self.Frame1_1.configure(highlightcolor="black")
        self.Frame1_1.configure(width=235)

        self.Label1_2 = Label(self.Frame1_1)
        self.Label1_2.place(relx=0.043, rely=0.222, height=26, width=25)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#d9d9d9")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(foreground="#000000")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''NE''')

        self.entry_ne1x = Entry(self.Frame1_1)
        self.entry_ne1x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_ne1x.configure(background="white")
        self.entry_ne1x.configure(disabledforeground="#a3a3a3")
        self.entry_ne1x.configure(font="TkFixedFont")
        self.entry_ne1x.configure(foreground="#000000")
        self.entry_ne1x.configure(highlightbackground="#d9d9d9")
        self.entry_ne1x.configure(highlightcolor="black")
        self.entry_ne1x.configure(insertbackground="black")
        self.entry_ne1x.configure(selectbackground="#c4c4c4")
        self.entry_ne1x.configure(selectforeground="black")

        self.entry_ne1y = Entry(self.Frame1_1)
        self.entry_ne1y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_ne1y.configure(background="white")
        self.entry_ne1y.configure(disabledforeground="#a3a3a3")
        self.entry_ne1y.configure(font="TkFixedFont")
        self.entry_ne1y.configure(foreground="#000000")
        self.entry_ne1y.configure(highlightbackground="#d9d9d9")
        self.entry_ne1y.configure(highlightcolor="black")
        self.entry_ne1y.configure(insertbackground="black")
        self.entry_ne1y.configure(selectbackground="#c4c4c4")
        self.entry_ne1y.configure(selectforeground="black")

        self.Frame1_5 = Frame(self.Labelframe4)
        self.Frame1_5.place(relx=0.04, rely=0.394, relheight=0.136, relwidth=0.94
                            , bordermode='ignore')
        self.Frame1_5.configure(relief=GROOVE)
        self.Frame1_5.configure(borderwidth="2")
        self.Frame1_5.configure(relief=GROOVE)
        self.Frame1_5.configure(background="#d9d9d9")
        self.Frame1_5.configure(highlightbackground="#d9d9d9")
        self.Frame1_5.configure(highlightcolor="black")
        self.Frame1_5.configure(width=235)

        self.Label1_6 = Label(self.Frame1_5)
        self.Label1_6.place(relx=0.043, rely=0.222, height=26, width=28)
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(text='''SW''')

        self.entry_sw1x = Entry(self.Frame1_5)
        self.entry_sw1x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_sw1x.configure(background="white")
        self.entry_sw1x.configure(disabledforeground="#a3a3a3")
        self.entry_sw1x.configure(font="TkFixedFont")
        self.entry_sw1x.configure(foreground="#000000")
        self.entry_sw1x.configure(highlightbackground="#d9d9d9")
        self.entry_sw1x.configure(highlightcolor="black")
        self.entry_sw1x.configure(insertbackground="black")
        self.entry_sw1x.configure(selectbackground="#c4c4c4")
        self.entry_sw1x.configure(selectforeground="black")

        self.entry_sw1y = Entry(self.Frame1_5)
        self.entry_sw1y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_sw1y.configure(background="white")
        self.entry_sw1y.configure(disabledforeground="#a3a3a3")
        self.entry_sw1y.configure(font="TkFixedFont")
        self.entry_sw1y.configure(foreground="#000000")
        self.entry_sw1y.configure(highlightbackground="#d9d9d9")
        self.entry_sw1y.configure(highlightcolor="black")
        self.entry_sw1y.configure(insertbackground="black")
        self.entry_sw1y.configure(selectbackground="#c4c4c4")
        self.entry_sw1y.configure(selectforeground="black")

        self.Frame1_9 = Frame(self.Labelframe4)
        self.Frame1_9.place(relx=0.04, rely=0.545, relheight=0.136, relwidth=0.94
                            , bordermode='ignore')
        self.Frame1_9.configure(relief=GROOVE)
        self.Frame1_9.configure(borderwidth="2")
        self.Frame1_9.configure(relief=GROOVE)
        self.Frame1_9.configure(background="#d9d9d9")
        self.Frame1_9.configure(highlightbackground="#d9d9d9")
        self.Frame1_9.configure(highlightcolor="black")
        self.Frame1_9.configure(width=235)

        self.Label1_10 = Label(self.Frame1_9)
        self.Label1_10.place(relx=0.043, rely=0.222, height=26, width=22)
        self.Label1_10.configure(activebackground="#f9f9f9")
        self.Label1_10.configure(activeforeground="black")
        self.Label1_10.configure(background="#d9d9d9")
        self.Label1_10.configure(disabledforeground="#a3a3a3")
        self.Label1_10.configure(foreground="#000000")
        self.Label1_10.configure(highlightbackground="#d9d9d9")
        self.Label1_10.configure(highlightcolor="black")
        self.Label1_10.configure(text='''SE''')

        self.entry_se1x = Entry(self.Frame1_9)
        self.entry_se1x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_se1x.configure(background="white")
        self.entry_se1x.configure(disabledforeground="#a3a3a3")
        self.entry_se1x.configure(font="TkFixedFont")
        self.entry_se1x.configure(foreground="#000000")
        self.entry_se1x.configure(highlightbackground="#d9d9d9")
        self.entry_se1x.configure(highlightcolor="black")
        self.entry_se1x.configure(insertbackground="black")
        self.entry_se1x.configure(selectbackground="#c4c4c4")
        self.entry_se1x.configure(selectforeground="black")

        self.entry_se1y = Entry(self.Frame1_9)
        self.entry_se1y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_se1y.configure(background="white")
        self.entry_se1y.configure(disabledforeground="#a3a3a3")
        self.entry_se1y.configure(font="TkFixedFont")
        self.entry_se1y.configure(foreground="#000000")
        self.entry_se1y.configure(highlightbackground="#d9d9d9")
        self.entry_se1y.configure(highlightcolor="black")
        self.entry_se1y.configure(insertbackground="black")
        self.entry_se1y.configure(selectbackground="#c4c4c4")
        self.entry_se1y.configure(selectforeground="black")

        self.btn_open_im1 = Button(self.Labelframe4)
        self.btn_open_im1.place(relx=0.52, rely=0.848, height=33, width=106
                                , bordermode='ignore')
        self.btn_open_im1.configure(activebackground="#d9d9d9")
        self.btn_open_im1.configure(activeforeground="#000000")
        self.btn_open_im1.configure(background="#d9d9d9")
        self.btn_open_im1.configure(disabledforeground="#a3a3a3")
        self.btn_open_im1.configure(foreground="#000000")
        self.btn_open_im1.configure(highlightbackground="#d9d9d9")
        self.btn_open_im1.configure(highlightcolor="black")
        self.btn_open_im1.configure(pady="0")
        self.btn_open_im1.configure(text='''Open Image 1''')

        self.btn_export = Button(top)
        self.btn_export.place(relx=0.866, rely=0.507, height=33, width=136)
        self.btn_export.configure(activebackground="#d9d9d9")
        self.btn_export.configure(activeforeground="#000000")
        self.btn_export.configure(background="#d9d9d9")
        self.btn_export.configure(disabledforeground="#a3a3a3")
        self.btn_export.configure(foreground="#000000")
        self.btn_export.configure(highlightbackground="#d9d9d9")
        self.btn_export.configure(highlightcolor="black")
        self.btn_export.configure(pady="0")
        self.btn_export.configure(text='''Export Result''')
        self.btn_export.configure(width=136)

        self.Labelframe4_14 = LabelFrame(top)
        self.Labelframe4_14.place(relx=0.384, rely=0.493, relheight=0.493
                                  , relwidth=0.223)
        self.Labelframe4_14.configure(relief=GROOVE)
        self.Labelframe4_14.configure(foreground="black")
        self.Labelframe4_14.configure(text='''Coors 1''')
        self.Labelframe4_14.configure(background="#d9d9d9")
        self.Labelframe4_14.configure(highlightbackground="#d9d9d9")
        self.Labelframe4_14.configure(highlightcolor="black")
        self.Labelframe4_14.configure(width=250)

        self.Frame1_15 = Frame(self.Labelframe4_14)
        self.Frame1_15.place(relx=0.04, rely=0.091, relheight=0.136
                             , relwidth=0.94, bordermode='ignore')
        self.Frame1_15.configure(relief=GROOVE)
        self.Frame1_15.configure(borderwidth="2")
        self.Frame1_15.configure(relief=GROOVE)
        self.Frame1_15.configure(background="#d9d9d9")
        self.Frame1_15.configure(highlightbackground="#d9d9d9")
        self.Frame1_15.configure(highlightcolor="black")
        self.Frame1_15.configure(width=235)

        self.Label1_16 = Label(self.Frame1_15)
        self.Label1_16.place(relx=0.043, rely=0.222, height=26, width=31)
        self.Label1_16.configure(activebackground="#f9f9f9")
        self.Label1_16.configure(activeforeground="black")
        self.Label1_16.configure(background="#d9d9d9")
        self.Label1_16.configure(disabledforeground="#a3a3a3")
        self.Label1_16.configure(foreground="#000000")
        self.Label1_16.configure(highlightbackground="#d9d9d9")
        self.Label1_16.configure(highlightcolor="black")
        self.Label1_16.configure(text='''NW''')

        self.entry_nw2x = Entry(self.Frame1_15)
        self.entry_nw2x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_nw2x.configure(background="white")
        self.entry_nw2x.configure(disabledforeground="#a3a3a3")
        self.entry_nw2x.configure(font="TkFixedFont")
        self.entry_nw2x.configure(foreground="#000000")
        self.entry_nw2x.configure(highlightbackground="#d9d9d9")
        self.entry_nw2x.configure(highlightcolor="black")
        self.entry_nw2x.configure(insertbackground="black")
        self.entry_nw2x.configure(selectbackground="#c4c4c4")
        self.entry_nw2x.configure(selectforeground="black")

        self.entry_nw2y = Entry(self.Frame1_15)
        self.entry_nw2y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_nw2y.configure(background="white")
        self.entry_nw2y.configure(disabledforeground="#a3a3a3")
        self.entry_nw2y.configure(font="TkFixedFont")
        self.entry_nw2y.configure(foreground="#000000")
        self.entry_nw2y.configure(highlightbackground="#d9d9d9")
        self.entry_nw2y.configure(highlightcolor="black")
        self.entry_nw2y.configure(insertbackground="black")
        self.entry_nw2y.configure(selectbackground="#c4c4c4")
        self.entry_nw2y.configure(selectforeground="black")

        self.Frame1_2 = Frame(self.Labelframe4_14)
        self.Frame1_2.place(relx=0.04, rely=0.242, relheight=0.136, relwidth=0.94
                            , bordermode='ignore')
        self.Frame1_2.configure(relief=GROOVE)
        self.Frame1_2.configure(borderwidth="2")
        self.Frame1_2.configure(relief=GROOVE)
        self.Frame1_2.configure(background="#d9d9d9")
        self.Frame1_2.configure(highlightbackground="#d9d9d9")
        self.Frame1_2.configure(highlightcolor="black")
        self.Frame1_2.configure(width=235)

        self.Label1_3 = Label(self.Frame1_2)
        self.Label1_3.place(relx=0.043, rely=0.222, height=26, width=25)
        self.Label1_3.configure(activebackground="#f9f9f9")
        self.Label1_3.configure(activeforeground="black")
        self.Label1_3.configure(background="#d9d9d9")
        self.Label1_3.configure(disabledforeground="#a3a3a3")
        self.Label1_3.configure(foreground="#000000")
        self.Label1_3.configure(highlightbackground="#d9d9d9")
        self.Label1_3.configure(highlightcolor="black")
        self.Label1_3.configure(text='''NE''')

        self.entry_ne2x = Entry(self.Frame1_2)
        self.entry_ne2x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_ne2x.configure(background="white")
        self.entry_ne2x.configure(disabledforeground="#a3a3a3")
        self.entry_ne2x.configure(font="TkFixedFont")
        self.entry_ne2x.configure(foreground="#000000")
        self.entry_ne2x.configure(highlightbackground="#d9d9d9")
        self.entry_ne2x.configure(highlightcolor="black")
        self.entry_ne2x.configure(insertbackground="black")
        self.entry_ne2x.configure(selectbackground="#c4c4c4")
        self.entry_ne2x.configure(selectforeground="black")

        self.entry_ne2y = Entry(self.Frame1_2)
        self.entry_ne2y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_ne2y.configure(background="white")
        self.entry_ne2y.configure(disabledforeground="#a3a3a3")
        self.entry_ne2y.configure(font="TkFixedFont")
        self.entry_ne2y.configure(foreground="#000000")
        self.entry_ne2y.configure(highlightbackground="#d9d9d9")
        self.entry_ne2y.configure(highlightcolor="black")
        self.entry_ne2y.configure(insertbackground="black")
        self.entry_ne2y.configure(selectbackground="#c4c4c4")
        self.entry_ne2y.configure(selectforeground="black")

        self.Frame1_6 = Frame(self.Labelframe4_14)
        self.Frame1_6.place(relx=0.04, rely=0.394, relheight=0.136, relwidth=0.94
                            , bordermode='ignore')
        self.Frame1_6.configure(relief=GROOVE)
        self.Frame1_6.configure(borderwidth="2")
        self.Frame1_6.configure(relief=GROOVE)
        self.Frame1_6.configure(background="#d9d9d9")
        self.Frame1_6.configure(highlightbackground="#d9d9d9")
        self.Frame1_6.configure(highlightcolor="black")
        self.Frame1_6.configure(width=235)

        self.Label1_7 = Label(self.Frame1_6)
        self.Label1_7.place(relx=0.043, rely=0.222, height=26, width=28)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''SW''')

        self.entry_sw2x = Entry(self.Frame1_6)
        self.entry_sw2x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_sw2x.configure(background="white")
        self.entry_sw2x.configure(disabledforeground="#a3a3a3")
        self.entry_sw2x.configure(font="TkFixedFont")
        self.entry_sw2x.configure(foreground="#000000")
        self.entry_sw2x.configure(highlightbackground="#d9d9d9")
        self.entry_sw2x.configure(highlightcolor="black")
        self.entry_sw2x.configure(insertbackground="black")
        self.entry_sw2x.configure(selectbackground="#c4c4c4")
        self.entry_sw2x.configure(selectforeground="black")

        self.entry_sw2y = Entry(self.Frame1_6)
        self.entry_sw2y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_sw2y.configure(background="white")
        self.entry_sw2y.configure(disabledforeground="#a3a3a3")
        self.entry_sw2y.configure(font="TkFixedFont")
        self.entry_sw2y.configure(foreground="#000000")
        self.entry_sw2y.configure(highlightbackground="#d9d9d9")
        self.entry_sw2y.configure(highlightcolor="black")
        self.entry_sw2y.configure(insertbackground="black")
        self.entry_sw2y.configure(selectbackground="#c4c4c4")
        self.entry_sw2y.configure(selectforeground="black")

        self.Frame1_10 = Frame(self.Labelframe4_14)
        self.Frame1_10.place(relx=0.04, rely=0.545, relheight=0.136
                             , relwidth=0.94, bordermode='ignore')
        self.Frame1_10.configure(relief=GROOVE)
        self.Frame1_10.configure(borderwidth="2")
        self.Frame1_10.configure(relief=GROOVE)
        self.Frame1_10.configure(background="#d9d9d9")
        self.Frame1_10.configure(highlightbackground="#d9d9d9")
        self.Frame1_10.configure(highlightcolor="black")
        self.Frame1_10.configure(width=235)

        self.Label1_11 = Label(self.Frame1_10)
        self.Label1_11.place(relx=0.043, rely=0.222, height=26, width=22)
        self.Label1_11.configure(activebackground="#f9f9f9")
        self.Label1_11.configure(activeforeground="black")
        self.Label1_11.configure(background="#d9d9d9")
        self.Label1_11.configure(disabledforeground="#a3a3a3")
        self.Label1_11.configure(foreground="#000000")
        self.Label1_11.configure(highlightbackground="#d9d9d9")
        self.Label1_11.configure(highlightcolor="black")
        self.Label1_11.configure(text='''SE''')

        self.entry_se2x = Entry(self.Frame1_10)
        self.entry_se2x.place(relx=0.213, rely=0.222, height=24, relwidth=0.357)
        self.entry_se2x.configure(background="white")
        self.entry_se2x.configure(disabledforeground="#a3a3a3")
        self.entry_se2x.configure(font="TkFixedFont")
        self.entry_se2x.configure(foreground="#000000")
        self.entry_se2x.configure(highlightbackground="#d9d9d9")
        self.entry_se2x.configure(highlightcolor="black")
        self.entry_se2x.configure(insertbackground="black")
        self.entry_se2x.configure(selectbackground="#c4c4c4")
        self.entry_se2x.configure(selectforeground="black")

        self.entry_se2y = Entry(self.Frame1_10)
        self.entry_se2y.place(relx=0.596, rely=0.222, height=24, relwidth=0.357)
        self.entry_se2y.configure(background="white")
        self.entry_se2y.configure(disabledforeground="#a3a3a3")
        self.entry_se2y.configure(font="TkFixedFont")
        self.entry_se2y.configure(foreground="#000000")
        self.entry_se2y.configure(highlightbackground="#d9d9d9")
        self.entry_se2y.configure(highlightcolor="black")
        self.entry_se2y.configure(insertbackground="black")
        self.entry_se2y.configure(selectbackground="#c4c4c4")
        self.entry_se2y.configure(selectforeground="black")

        self.btn_open_im2 = Button(self.Labelframe4_14)
        self.btn_open_im2.place(relx=0.52, rely=0.848, height=33, width=106
                                , bordermode='ignore')
        self.btn_open_im2.configure(activebackground="#d9d9d9")
        self.btn_open_im2.configure(activeforeground="#000000")
        self.btn_open_im2.configure(background="#d9d9d9")
        self.btn_open_im2.configure(disabledforeground="#a3a3a3")
        self.btn_open_im2.configure(foreground="#000000")
        self.btn_open_im2.configure(highlightbackground="#d9d9d9")
        self.btn_open_im2.configure(highlightcolor="black")
        self.btn_open_im2.configure(pady="0")
        self.btn_open_im2.configure(text='''Open Image 2''')


if __name__ == '__main__':
    vp_start_gui()
